# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: JFrogNpm@1
  inputs:
    command: 'install'
    artifactoryConnection: 'hts2v2artifactory'
    sourceRepo: 'ca-npm'